### PR TITLE
Added PS tags and phased genotypes when decomposin complex variants

### PR DESCRIPTION
**Pull request by andyrimmer**
I've added the basic functionality, with a '-p' command-line flag. It adds a 'PS' tag with the position of the first variant in the decomposed block as an ID, and replaces the '/' with a '|' in the GT field. I've tested this on a few small VCFs, and it seems to work fine, but it took me a little while to work out how to modify the genotypes, so it's worth checking over that code.

### CODE REVIEW

**Comment by atks** [comment]
May I have access to your small VCFs for testing?

**Comment by andyrimmer** [comment]
I used this for testing MNP splitting with phased genotypes. I have not
tested on length-changing replacements
yet.

Andy

On Mon, Feb 8, 2016 at 2:50 PM, Adrian Tan <notifications@github.com> wrote:

> May I have access to your small VCFs for testing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atks/vt/pull/42#issuecomment-181399503>.
>

-- 
This email is sent on behalf of Genomics plc, a public limited company 
registered in England and Wales with registered number 8839972, VAT 
registered number 189 2635 65 and registered office at 24 Cornhill, London, 
EC3V 3ND, United Kingdom.
The contents of this e-mail and any attachments are confidential to the 
intended recipient. If you are not the intended recipient please do not use 
or publish its contents, contact Genomics plc immediately at 
info@genomicsplc.com <info@genomicsltd.com> then delete. You may not copy, 
forward, use or disclose the contents of this email to anybody else if you 
are not the intended recipient. Emails are not secure and may contain 
viruses.

**Comment by atks** [comment]
I've updated a test set in make test.
There was a bug which killed the program when there are more than one individual in a VCF file.

Use case updated in wiki page
http://genome.sph.umich.edu/wiki/Vt#Decompose_biallelic_block_substitutions

There might be a better way to name the phase set IDs for the second individual.

**Comment by andyrimmer** [comment]
Sorry about that: I should have tested on multi-sample VCFs. I think the
phase set ID should be the same across individuals.  In the example on the
Wiki the tumour and normal samples end up with different PS values, but as
far as I can see from the code there is only one call to

bcf_update_format_int32(odw->hdr, nv, "PS", &start_pos_of_phased_block,
bcf_get_n_sample(nv));

so how do they end up with different values?

Kind regards,
Andy

On Mon, Feb 8, 2016 at 8:14 PM, Adrian Tan <notifications@github.com> wrote:

> I've updated a test set in make test.
> There was a bug which killed the program when there are more than one
> individual in a VCF file.
>
> Use case updated in wiki page
> http://genome.sph.umich.edu/wiki/Vt#Decompose_biallelic_block_substitutions
>
> There might be a better way to name the phase set IDs for the second
> individual.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atks/vt/pull/42#issuecomment-181511992>.
>

-- 
This email is sent on behalf of Genomics plc, a public limited company 
registered in England and Wales with registered number 8839972, VAT 
registered number 189 2635 65 and registered office at 24 Cornhill, London, 
EC3V 3ND, United Kingdom.
The contents of this e-mail and any attachments are confidential to the 
intended recipient. If you are not the intended recipient please do not use 
or publish its contents, contact Genomics plc immediately at 
info@genomicsplc.com <info@genomicsltd.com> then delete. You may not copy, 
forward, use or disclose the contents of this email to anybody else if you 
are not the intended recipient. Emails are not secure and may contain 
viruses.

**Comment by atks** [comment]
fixed.  when updating, you need to update from an array of n_sample values.  so the fix was to simply make sure that start_pos_of_phased_block was an array and that it was properly updated.  unequal allele length variants also tested out fine.

**Comment by andyrimmer** [comment]
Great. Thanks for that.
On 8 Feb 2016 21:51, "Adrian Tan" <notifications@github.com> wrote:

> fixed. when updating, you need to update from an array of n_sample values.
> so the fix was to simply make sure that start_pos_of_phased_block was an
> array and that it was properly updated. unequal allele length variants also
> tested out fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atks/vt/pull/42#issuecomment-181572278>.
>

-- 
This email is sent on behalf of Genomics plc, a public limited company 
registered in England and Wales with registered number 8839972, VAT 
registered number 189 2635 65 and registered office at 24 Cornhill, London, 
EC3V 3ND, United Kingdom.
The contents of this e-mail and any attachments are confidential to the 
intended recipient. If you are not the intended recipient please do not use 
or publish its contents, contact Genomics plc immediately at 
info@genomicsplc.com <info@genomicsltd.com> then delete. You may not copy, 
forward, use or disclose the contents of this email to anybody else if you 
are not the intended recipient. Emails are not secure and may contain 
viruses.

**Pull request merged**
