### PR TITLE
Add option to keep close MNVs in decompose_blocksub

### PR DESCRIPTION
**Pull request by jaudoux**
Dear VT developpers,

I have implemented a new option in the `decompose_blocksub` module in order to keep close MNVs (max 2bp away by default) together and not decompose them into their constituent SNPs. 

This is really important for MNVs that belong to the same codon as the predicted effect can be quite different depending if their interpreted together or independently (see recent bibliography on the matter bellow).

Let me know if the implementation met your acceptance criterion.

Jérôme.

**Limitations**
Their is currently two limitations with the implementation that I propose:

- `-m` option wont work for complex variants (`length(ref) != length(alt)`) that are decomposed when the `-a` option is used
- `-m` option wont work with `-p` option. It's just that I don't really get this part of the code and I dont want to mess it up!

**Biblio on MNVs**:

- Exome-wide assessment of the functional impact and pathogenicity of multi-nucleotide mutations https://www.biorxiv.org/content/10.1101/258723v2.full 
- Landscape of multi-nucleotide variants in 125,748 human exomes and 15,708 genomes https://www.biorxiv.org/content/10.1101/573378v2.full

### CODE REVIEW

**Comment by atks** [comment]
@jaudoux 

let me think about this for a bit.

**Comment by jaudoux** [comment]
@atks, if I can help with your thinking, let me know!

**Comment by jaudoux** [comment]
@atks have you thought about it ?

**Comment by atks** [comment]
@jaudoux  - have the papers been accepted yet?  I think they are still in preprints.  I am willing to accept the pull requests once it has passed peer review and are officially published.

**Comment by atks** [comment]
> @jaudoux - have the papers been accepted yet? I think they are still in preprints. I am willing to accept the pull requests once it has passed peer review and are officially published.

I found the earlier paper on Genome Research.
"Exome-wide assessment of the functional impact and pathogenicity of multinucleotide mutations"
https://genome.cshlp.org/content/early/2019/06/21/gr.239756.118.abstract

Is the new function used in the landscape paper as well as this earlier paper?

**Comment by jaudoux** [comment]
Hi @atks , 

Just to clarify the situation I am not the author of the papers that I have cited in my PR. It was a way to point out the need of improving VT decomposition step to avoid splitting multi-nucleotide variants that should be interpreted together.

Both papers, "landscape" from GnomAD team and "Exome-wide" from DECIPHER team, uses GATK Haplotype caller which (by default) decomposed all MNVs. They later phased variants with either a read-based strategy or trio-based strategy.

Currently GATK supports a `--max-mnp-distance` that is the equivalent of what I implemented in VT `decompose_blocksub` to work with all haplotype callers.

Let me know if this is clear to you.

Best,
J.

**Comment by atks** [comment]
@jaudoux - I've merged it first since the code is safely compartmentalized.  Will still need to test on a genotype VCF file.  And I wonder how it should function with the -a option. 

The wiki is updated: https://genome.sph.umich.edu/wiki/Vt#Decompose_biallelic_block_substitutions
with your contribution stated. Thanks for your contribution!

**Comment by atks** [comment]
@jaudoux - it might also be a good idea to just have one option. Since -d 0 essentially forces the decomposition of all MNPs, so allow -m to take integer values with 0 to be false and positive numbers to be the distance for preserving the MNP.

**Pull request merged**
